version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
    environment:
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_NAME=product_register_development
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_register_development
    volumes:
      - 'db-data:/var/lib/postgresql/data'
